#!/bin/sh
#
# $OpenBSD: winbindd.rc,v 1.7 2015/08/25 11:07:45 jca Exp $

smbcontrol="/usr/local/bin/smbcontrol"

daemon="/usr/local/sbin/winbindd -D"

. /etc/rc.d/rc.subr

rc_usercheck=NO

rc_check() {
	${smbcontrol} winbindd ping
}

rc_reload() {
	${smbcontrol} winbindd reload-config
}

rc_stop() {
	${smbcontrol} winbindd shutdown
}

rc_cmd $1
